### ISSUE TITLE
Maybe change `_file` to update existing dictionary rather than replacing it?

### ISSUE THREAD

**Issue by fferflo** [mattiasarro/confr#1]
Hey, I love this library!

As far as I understand, using `_file` removes all existing keys at the same tree level and replaces them with the content of the file, like so:

```yaml
# conf/base.yaml
sub:
  a: 1 # Is removed when _file is loaded
  _file: update

# conf/sub/update.yaml
b: 2

# Result:
sub:
  b: 2
```

What do you think about updating the existing dictionary with the file values instead? The result would then be:

```yaml
# Result:
sub:
  a: 1
  b: 2
```

This would keep existing keys and would essentially work like default values for the loaded file, so that common values do not have to repeated in every file I could import. 

The tree would ideally be updated recursively, so something like this might work:

```diff
+ def _update_recursively(node, key, update):
+     if isinstance(node[key], dict) and isinstance(update, dict):
+         for k, v in update.items():
+             if k in node[key]:
+                 _update_recursively(node[key], k, v)
+             else:
+                 node[key][k] = v
+     else:
+         node[key] = update

...

In https://github.com/mattiasarro/confr/blob/main/src/confr/models.py#L119
- conf_dict[k] = read_yaml(conf_fp, verbose=verbose)
+ _update_recursively(conf_dict, k, read_yaml(conf_fp, verbose=verbose))
+ del conf_dict[k]["_file"]
```
